booking/urls.py
from django.contrib import admin
from django.urls import path, include

from hotels.views import page_not_found
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hotels.urls')),
    path('users/', include('users.urls', namespace="users", )),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = page_not_found

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, include, reverse_lazy
from . import views

app_name = "users"


urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    # path('logout/', LogoutView.as_view(), name='logout'),
    # path('register/', views.register, name='register'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/',
         PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),


    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy("users:password_reset_done")),
        name='password_reset')
    ,
    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
        name='password_reset_done'),


    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),

    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html',),
        name='password_reset_complete'),



    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),

]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label="логин", widget=forms.TextInput(attrs={'class': 'login-page__form-input-box'}))
    password = forms.CharField(label="пароль", widget=forms.PasswordInput(attrs={'class': 'login-page__form-input-box'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label="логин")
    password1 = forms.CharField(label="пароль", widget=forms.PasswordInput(attrs={'class': 'login-page__form-input-box'}))
    password2 = forms.CharField(label="повтор пароля", widget=forms.PasswordInput(attrs={'class': 'login-page__form-input-box'}))


    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widget = {
            'email': forms.PasswordInput(attrs={'class': 'login-page__form-input-box'}),
            'first_name': forms.PasswordInput(attrs={'class': 'login-page__form-input-box'}),
            'last_name': forms.PasswordInput(attrs={'class': 'login-page__form-input-box'}),
        }



    # def cleen_password2(self):
    #     cd = self.cleaned_data
    #     if cd['password'] != cd['passworfd2']:
    #         raise forms.ValidationError('Пароли не совпадают')
    #     return cd['password']

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Такой e-mail уже зареген!')
        return email



class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label="логин", widget=forms.TextInput(attrs={'class': 'login-page__form-input-box'}))
    email = forms.CharField(disabled=True, label="E-mail", widget=forms.TextInput(attrs={'class': 'login-page__form-input-box'}))


    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widget = {
            'first_name': forms.PasswordInput(attrs={'class': 'login-page__form-input-box'}),
            'last_name': forms.PasswordInput(attrs={'class': 'login-page__form-input-box'}),
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'login-page__form-input-box'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'login-page__form-input-box'}))
    new_password2 = forms.CharField(label="Новый пароль повтор", widget=forms.PasswordInput(attrs={'class': 'login-page__form-input-box'}))

users/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView

from .forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}

    # def success_url(self):
    #     return reverse_lazy('home')


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'

    extra_context = {
        'title': 'Регистрация',
    }
    success_url = reverse_lazy('users:login')


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': 'Профиль пользователя'}

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"

users/templates/users/login.html
{% extends '.\base.html' %}
{% load static %}


{% block content %}
    <section class="login-page">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 wow fadeInUp animated" data-wow-delay="300ms">
                    <div class="login-page__wrap">
                        <h3 class="login-page__wrap__title">Авторизация</h3>

                        <form class="login-page__form" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ next }}">
                            <div class="form-error">{{ form.non_field_error }}</div>
                            {#                                {{ form.as_p }}#}
                            {% for f in form %}
                                <div><label class="login-page__form-input-box"
                                            for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</div>
                                <div class="form-errors"> {{ f.errors }}</div>
                            {% endfor %}
                            <div class="login-page__form-btn-box">
                                <button type="submit" class="villoz-btn">
                                    <i>Войти</i>
                                    <span>Войти</span>
                                </button>
                                <div class="login-page__form-forgot-password">
                                    <a href="{% url 'users:password_reset' %} ">Напомнить пароль?</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-6 wow fadeInUp animated" data-wow-delay="300ms">
                    <div class="login-page__wrap">
                        <img src="{% static 'hotels/images/checkin.png' %}" alt='{{ hotel.title }}'/>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

users/templates/users/password_change_done.html
{% extends '.\base.html' %}
{% load static %}


{% block content %}

    <p>Пароль изменён</p>
    <a href="{% url 'users:profile' %}">Вернуться в профиль</a>
{% endblock %}

users/templates/users/password_change_form.html
{% extends '.\base.html' %}
{% load static %}


{% block content %}

    <section class="login-page">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 wow fadeInUp animated" data-wow-delay="300ms">
                    <div class="login-page__wrap">
                        <h3 class="login-page__wrap__title">Изменить пароль</h3>

                        <form class="login-page__form" method="POST">
                            {% csrf_token %}
                            <div class="form-error">{{ form.non_field_error }}</div>
                            {% for f in form %}
                            <div><label class="login-page__form-input-box"
                                      for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</div>
                            <div class="form-errors"> {{ f.errors }}</div>
                            {% endfor %}
                            <p></p>
                            <div class="login-page__form-btn-box">
                                    <button type="submit" class="villoz-btn">
                                        <i>Изменить пароль</i>
                                        <span>Изменить</span>
                                    </button>
                                </div>
                        </form>


                    </div>
                </div>
                <div class="col-lg-6 wow fadeInUp animated" data-wow-delay="300ms">
                     <div class="login-page__wrap">
                    <img src="{% static 'hotels/images/registration.png' %}" alt='{{ hotel.title }}'/>
                     </div>
                </div>

            </div>

        </div>
    </section>


{% endblock %}

users/templates/users/password_reset_complete.html
{% extends '.\base.html' %}
{% load static %}

<h1>Пароль изменён</h1>
<a href="{% url 'users:login' %}">Вход в систему</a>
{% block content %}
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends '.\base.html' %}
{% load static %}


{% block content %}

    <section class="login-page">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 wow fadeInUp animated" data-wow-delay="300ms">
                    <div class="login-page__wrap">
                        <h3 class="login-page__wrap__title">Новый пароль</h3>

                        <form class="login-page__form" method="POST">
                            {% csrf_token %}
                            <div class="form-error">{{ form.non_field_error }}</div>
                            {% for f in form %}
                            <div><label class="login-page__form-input-box"
                                      for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</div>
                            <div class="form-errors"> {{ f.errors }}</div>
                            {% endfor %}
                            <p></p>
                            <div class="login-page__form-btn-box">
                                    <button type="submit" class="villoz-btn">
                                        <i>Сохранить</i>
                                        <span>Сохранить</span>
                                    </button>
                                </div>
                        </form>


                    </div>
                </div>
                <div class="col-lg-6 wow fadeInUp animated" data-wow-delay="300ms">
                     <div class="login-page__wrap">
                    <img src="{% static 'hotels/images/registration.png' %}" alt='{{ hotel.title }}'/>
                     </div>
                </div>

            </div>

        </div>
    </section>


{% endblock %}

users/templates/users/password_reset_done.html
{% extends '.\base.html' %}
{% load i18n %}


{% block content %}
<h1>Сброс пароля</h1>

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends '.\base.html' %}
{% load static %}


{% block content %}

    <section class="login-page">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 wow fadeInUp animated" data-wow-delay="300ms">
                    <div class="login-page__wrap">
                        <h3 class="login-page__wrap__title">Сброс пароля</h3>

                        <form class="login-page__form" method="POST">
                            {% csrf_token %}
                            <div class="form-error">{{ form.non_field_error }}</div>
                            {% for f in form %}
                            <div><label class="login-page__form-input-box"
                                      for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</div>
                            <div class="form-errors"> {{ f.errors }}</div>
                            {% endfor %}
                            <p></p>
                            <div class="login-page__form-btn-box">
                                    <button type="submit" class="villoz-btn">
                                        <i>Сбросить пароль по E-mail</i>
                                        <span>Сбросить пароль по E-mail</span>
                                    </button>
                                </div>
                        </form>


                    </div>
                </div>
                <div class="col-lg-6 wow fadeInUp animated" data-wow-delay="300ms">
                     <div class="login-page__wrap">
                    <img src="{% static 'hotels/images/registration.png' %}" alt='{{ hotel.title }}'/>
                     </div>
                </div>

            </div>

        </div>
    </section>


{% endblock %}

users/templates/users/profile.html
{% extends '.\base.html' %}
{% load static %}


{% block content %}

    <section class="login-page">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 wow fadeInUp animated" data-wow-delay="300ms">
                    <div class="login-page__wrap">
                        <h3 class="login-page__wrap__title">Профиль пользователя</h3>

                        <form class="login-page__form" method="POST">
                            {% csrf_token %}
                        <input type="hidden" name="next" value="{{ next }}">
                            <div class="form-error">{{ form.non_field_error }}</div>
                            {% for f in form %}
                            <div><label class="login-page__form-input-box"
                                      for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</div>
                            <div class="form-errors"> {{ f.errors }}</div>
                            {% endfor %}
                            <p></p>
                            <div class="login-page__form-btn-box">
                                    <button type="submit" class="villoz-btn">
                                        <i>Сохранить</i>
                                        <span>Сохранить</span>
                                    </button>
                                </div>
                        </form>
                        <br>
                    <p><a href="{% url 'users:password_change' %}">Поменять пароль</a></p>
                    </div>
                </div>
                <div class="col-lg-6 wow fadeInUp animated" data-wow-delay="300ms">
                     <div class="login-page__wrap">
                    <img src="{% static 'hotels/images/registration.png' %}" alt='{{ hotel.title }}'/>
                     </div>
                </div>

            </div>

        </div>
    </section>


{% endblock %}

users/templates/users/register.html
{% extends '.\base.html' %}
{% load static %}


{% block content %}
    <section class="login-page">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 wow fadeInUp animated" data-wow-delay="300ms">
                    <div class="login-page__wrap">
                        <h3 class="login-page__wrap__title">Регистрация</h3>

                        <form class="login-page__form" method="POST">
                            {% csrf_token %}
                        <input type="hidden" name="next" value="{{ next }}">
                            <div class="form-error">{{ form.non_field_error }}</div>
                            {% for f in form %}
                            <div><label class="login-page__form-input-box"
                                      for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</div>
                            <div class="form-errors"> {{ f.errors }}</div>
                            {% endfor %}
                            <p></p>
                            <div class="login-page__form-btn-box">
                                    <button type="submit" class="villoz-btn">
                                        <i>Регистрация</i>
                                        <span>Регистрация</span>
                                    </button>
                                </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-6 wow fadeInUp animated" data-wow-delay="300ms">
                     <div class="login-page__wrap">
                    <img src="{% static 'hotels/images/registration.png' %}" alt='{{ hotel.title }}'/>
                     </div>
                </div>

            </div>

        </div>
    </section>
{% endblock %}

users/templates/users/register_done.html
{% extends '.\base.html' %}
{% load static %}


{% block content %}
    <h1>Добро пожаловать</h1>
    <section class="login-page">
        <div class="container">
            <div class="row">
                <p>Вы успешно зарегестрировались на сайте! Для входа необходимо авторизироваться!!!!</p>
                <a href="{% url 'users:login' %}">Войти</a>
            </div>
        </div>
    </section>
{% endblock %}