booking/urls.py
from django.contrib import admin
from django.urls import path, include

from hotels.views import page_not_found
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hotels.urls')),
    path('users/', include('users.urls', namespace="users", )),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = page_not_found

hotels/urls.py
from django.contrib import admin
from django.urls import path, re_path, register_converter
from . import views
from . import converters

register_converter(converters.FourDigitYearConverter, 'year4')

urlpatterns = [

    path('', views.index, name='home'),

    path('city/<slug:city_slug>/', views.show_category, name='category'),

    path('hotels/', views.HotelsList.as_view(), name='hotels_list'),

    path('hotels/<slug:hotel_slug>/', views.hotel_detail, name='hotel_detail'),

    path('hotels/<slug:hotel_slug>/<slug:room_slug>/', views.room_detail, name='room_detail'),

    path('book/', views.room_detail_book, name='room_detail_book'),

    path('book/my/', views.get_my_book, name='get_my_book'),

#-------------------------------------------------------------------
    path('addhotel/', views.AddHotel.as_view(), name='add_hotel'),
    path('edit/<slug:slug>/', views.UpdateHotel.as_view(), name='hotel_edit'),
    path('addroom/', views.AddRoom.as_view(), name='add_room'),
#-------------------------------------------------------------------
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),


]

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, include, reverse_lazy
from . import views

app_name = "users"


urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    # path('logout/', LogoutView.as_view(), name='logout'),
    # path('register/', views.register, name='register'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/',
         PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),


    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy("users:password_reset_done")),
        name='password_reset')
    ,
    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
        name='password_reset_done'),


    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),

    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html',),
        name='password_reset_complete'),



    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),

]

hotels/forms.py
import datetime
from datetime import date
from django import forms
from django.forms import SelectDateWidget

from .models import Room, Booking, Hotel, Comment


class AddHotelForm(forms.ModelForm):

    class Meta:
        model = Hotel
        fields = ['title', 'slug', 'location_city', 'location_strit', 'location_building', 'short_desc', 'description', 'rating', 'logo_hotel', 'recomended', 'status']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'from-input'}),
            'description': forms.Textarea(attrs={'cols': 50, 'rows': 10}),
        }

        labels = {'slug': 'URL'}


class AddRoomForm(forms.ModelForm):

    class Meta:
        model = Room
        fields = [
            'title',
            'slug',
            'hotel_id',
            'room_type',
            'price_per_night',
            'short_desc',
            'description',
            'status',
        ]

        widgets = {
            'title': forms.TextInput(attrs={'class': 'from-input'}),
            'description': forms.Textarea(attrs={'cols': 50, 'rows': 10}),
            'room_type': forms.Select(attrs={'class': 'filter-option-inner'})

        }

        labels = {'slug': 'URL'}


class BookingForm(forms.ModelForm):

    class Meta:

        model = Booking
        fields = [
            'check_in',
            'check_out',
        ]
        YEARS = [str(year) for year in range(date.today().year, date.today().year + 1)]
        labels = {
            'check_in': 'Дата заезда',
            'check_out': 'Дата выезда',
        }
        widgets = {
                    # 'check_in': forms.SelectDateWidget(years=range(date.today().year, date.today().year + 2),),
                    # 'check_out': forms.SelectDateWidget(years=range(date.today().year, date.today().year + 2)),
            'check_in': forms.TextInput(attrs={'type': "date", 'name': "date"}),
            'check_out': forms.TextInput(attrs={'type': "date", 'name': "date"})

            }

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text', 'rating')

        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-one__control', 'cols': '100', 'rows': 5, 'resise': 'revert'}),
        }

hotels/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render, redirect, get_object_or_404
from django.template import context
from django.template.defaultfilters import slugify
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, ListView, \
    DetailView, FormView, CreateView, UpdateView
from .forms import AddHotelForm, AddRoomForm, BookingForm, CommentForm

from .models import Hotel, Room, HotelMedia, RoomMedia, City, Booking

from django.views.decorators.http import require_POST


def index(request):
    hotels = Hotel.published.all()

    data = {
        'title': 'Главная',
        'hotels': hotels,
        'cat_selected': 0,
    }
    return render(request, 'hotels/index.html', context=data)


def show_category(request, city_slug):
    category = get_object_or_404(City, slug=city_slug)
    hotels = Hotel.objects.filter(location_city=category.pk)
    data = {

        'title': f'Отели города: {category.title}',
        'hotels': hotels,
        'cat_selected': category.pk,
    }
    return render(request, 'hotels/index.html', context=data)


class HotelsHome(TemplateView):
    template_name = 'hotels/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Главная страница'

        return context


class AddHotel(LoginRequiredMixin, CreateView):
    form_class = AddHotelForm
    # model = Hotel
    # fields = '__all__'
    template_name = 'hotels/add_hotel.html'
    # success_url = reverse_lazy('home')
    extra_context = {

        'title': 'Добавить отель',
    }

    def form_valid(self, form):
        w = form.save(commit=False)
        w.author = self.request.user
        return super().form_valid(form)


class UpdateHotel(UpdateView):
    model = Hotel
    fields = ['title', 'logo_hotel', 'short_desc', 'description',
              'rating', 'location_city', 'location_strit',
              'location_building', 'recomended', ]
    template_name = 'hotels/add_hotel.html'
    success_url = reverse_lazy('home')
    extra_context = {

        'title': 'Редактировать отель',
    }


# -------------------------------------------------------------------
class AddRoom(LoginRequiredMixin, CreateView):
    form_class = AddRoomForm
    template_name = 'hotels/add_room.html'
    # success_url = reverse_lazy('home')
    extra_context = {

        'title': 'Добавить номер',
    }

    def form_valid(self, form):
        w = form.save(commit=False)
        w.author = self.request.user
        return super().form_valid(form)


class UpdateRoom(UpdateView):
    model = Room
    fields = ['title', 'hotel_id', 'room_type', 'price_per_night', 'short_desc', 'description', 'status']
    template_name = 'hotels/add_room.html'
    success_url = reverse_lazy('home')
    extra_context = {

        'title': 'Редактировать номер',
    }





class HotelsList(ListView):
    city = City.objects.all()
    # model = Hotel
    title = 'Отели'
    # hotels = Hotel.objects.filter(status=True)
    template_name = 'hotels/hotels_list.html'
    context_object_name = 'hotels'
    paginate_by = 6

    extra_context = {
        # 'hotels': hotels,

        'title': title,
        'paginate_by': paginate_by,
        'city_select': 0,
    }

    def get_queryset(self):
        return Hotel.published.all()


def hotel_detail(request, hotel_slug):
    hotel = get_object_or_404(Hotel, slug=hotel_slug)
    rooms = Room.published.filter(hotel_id=hotel.pk)
    photos = HotelMedia.objects.filter(hotel_id=hotel.pk)

    date = {
        'title': hotel.title,
        'hotel': hotel,
        'rooms': rooms,
        'photos': photos,
    }

    return render(request, 'hotels/hotel_detail.html', date)


# @login_required(login_url='/users/login/')
def room_detail(request, hotel_slug, room_slug):
    hotel = get_object_or_404(Hotel, slug=hotel_slug)
    room = get_object_or_404(Room, slug=room_slug)
    photos = RoomMedia.objects.filter(room_id=room.pk)

    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            booking = form.save(commit=False)
            booking.user = request.user
            booking.room = room
            booking.save()
            return render(request, 'hotels/book_room.html', {'room': room, 'hotel': hotel})
    else:
        form = BookingForm()

    if request.method == 'POST':
        form3 = CommentForm(request.POST)
        if form3.is_valid():
            comment = form3.save(commit=False)
            comment.room = room
            comment.author = request.user
            comment.save()
            return redirect('room_detail', hotel_slug, room_slug)
    else:
        form3 = CommentForm()

    date = {
        'room': room,
        'hotel': hotel,
        'title': room.title,
        'room_type': room.room_type,
        'price_per_night': room.price_per_night,
        'description': room.description,
        'created_at': room.created_at,
        'updated_at': room.updated_at,
        'photos': photos,

        'form': form,
        'form3': form3,

    }


    return render(request, 'hotels/room_detail.html', date)


def room_detail_book(request, room, hotel, user):
    title = 'Успешно забронировали номер'
    # user = get_object_or_404(User, slug=hotel.pk)
    hotel = get_object_or_404(Hotel, slug=hotel.pk)
    room = get_object_or_404(Room, slug=room.pk)

    date = {
        'title': title,
        'hotel': hotel,
        'room': room,
   }

    return render(request, 'hotels/book_room.html', date)


def get_my_book(request):
    book = Booking.objects.filter(user=request.user.pk)
    date = {
        'book': book,

    }
    return render(request, 'hotels/my_book.html', date)

# def available_rooms(request):
#     rooms = Room.objects.filter(is_booked=False)
#     return render(request, 'available_rooms.html', {'rooms': rooms})


# def book_room(request, room_id):
#     room = Room.objects.get(id=room_id)
#     if request.method == 'POST':
#         form = BookingForm(request.POST)
#         if form.is_valid():
#             booking = form.save(commit=False)
#             booking.user = request.user
#             booking.room = room
#             booking.save()
#             return redirect('success_page')  # Перенаправление на страницу успеха
#     else:
#         form = BookingForm()
#     return render(request, 'hotels/book_room.html', {'form': form, 'room': room})


def page_not_found(request, exception):
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')



# @login_required(login_url='/users/login/')
def about(request):
    data = {
        'title': 'О компании',
    }
    return render(request, 'hotels/about.html', context=data)


def contact(request):
    data = {
        'title': 'Обратная связь',

    }
    return render(request, 'hotels/contact.html', context=data)

hotels/templates/hotels/about2.html
{% extends '.\base.html' %}
{% load static %}


{% block content %}
<h1>{{ title }}</h1>

{% for city in city_list %}

    {{ city.title }}
    {% for hotel in hotel_list %}
        {{ hotel.t }}
        {% endfor %}
{% endfor %}

{% endblock %}

hotels/templates/hotels/add_hotel.html
{% extends '.\base.html' %}
{% load static %}
{% block content %}

    <section class="checkout-page">
            <div class="container">
                <form class="checkout-page__form" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-errors"> {{ from.non_field_errors }}</div>
                   {% for f in form %}
                    <div class="checkout-page__input-box"><label class="checkout-page__input-box" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</div>
                        <div class="form-errors"> {{ f.field_errors }}</div>
                   {% endfor %}
                    <p><button type="submit">Отправить</button></p>
                </form>

            </div>
    </section>
{% endblock %}

hotels/templates/hotels/add_room.html
{% extends '.\base.html' %}
{% load static %}
{% block content %}

    <section class="checkout-page">
            <div class="container">
                <form class="checkout-page__form" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-errors"> {{ from.non_field_errors }}</div>
                   {% for f in form %}
                    <div class="checkout-page__input-box"><label class="checkout-page__input-box" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</div>
                        <div class="form-errors"> {{ f.field_errors }}</div>
                   {% endfor %}
                    <p><button type="submit">Отправить</button></p>
                </form>

            </div>
    </section>
{% endblock %}

hotels/templates/hotels/book_room.html
{% extends '.\base.html' %}
{% load static %}
{% load my_filters %}



{% block content %}


    <section class="villa-details-three">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p>Уважаемый {{ user.username }}</p>
                   <p>Вы успешно забронировали номер:</p>
                   <p>Отель: {{ hotel.title }} <a href="{{ hotel.get_absolute_url }}">ПЕРЕЙТИ</a></p>
                   <p>Номер: {{ room.title }} <a href="{{ room.get_absolute_url }}">Вернуться</a></p>

                    <p>Посмотреть все мои заказы<a href="{% url 'get_my_book' %}">ПОСМОТРЕТЬ</a></p>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

hotels/templates/hotels/booking_form.html
{#   {% extends 'base.html' %}#}
{#{% load static %}#}
{#{% block content %}#}
{##}
{##}
{#    <form method="post">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <button type="submit">Забронировать</button>#}
{#    </form>#}
{#   {% endblock %}#}

hotels/templates/hotels/comment.html
{% extends '.\base.html' %}
{% load static %}

{% block title %}Добавить комментарий{% endblock %}
{% block content %}
    {% if comment %}
        <h2>Ваш комментарий был добавлен.</h2>
        <p><a href="{{ room.get_absolute_url }}">Вернуться</a></p>
    {% else %}
        {% include "hotels/comment_form.html" %}
    {% endif %}
{% endblock %}

hotels/templates/hotels/comment_form.html
<h2>Добавить новый комментарий</h2>
<form action="{% url "post_comment" hotel.slug room.slug %}" method="post">
{{ form2.as_p }}
{% csrf_token %}
<p><input type="submit" value="Добавить комментарий"></p>
</form>

hotels/templates/hotels/list_categories.html
{% for cat in cats %}
    {% if cat.slug == cat_selected %}
        <li class="selected">{{ cat.title }}</li>
    {% else %}
        <li><a href="{{ cat.get_absolute_url }}">{{ cat.title }}</a></li>
    {% endif %}
{% endfor %}

hotels/templates/hotels/list_city.html
{% for city in cities %}

    {% if city.id == city_select %}
        <li class="selected">!{{ city.title }}</li>
        {% else %}
        <li><a href="{{ city.get_absolute_url }}">{{ city.title }}</a></li>
    {% endif %}

{% endfor %}

hotels/templates/hotels/room_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <section class="villa-details-one">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-xl-5">
                    <div class="villa-details-one__info">
                        <p class="villa-details-one__address"><b>{{ hotel.title }}</b> / {{ hotel.location_city }}, {{ hotel.location_strit }}, {{ hotel.location_building }}</p>


                        <h3 class="villa-details-one__title">{{ room.title }}</h3>
                        <div class="villa-details-one__price-wrap">
                            <div class="villa-details-one__price"> {{ room.price_per_night }} BYN <span
                                    class="villa-details-one__price__shift">/ ночь</span></div>

                        </div>
                    </div>
                </div>
                <div class="col-lg-8 col-xl-7">
                    <div class="villa-details-one__meta">
                        <div class="villa-details-one__meta__item">
                            <div class="villa-details-one__meta__icon"><span class="icon-bed"></span></div>
                            <h5 class="villa-details-one__meta__number">{{ room.bads }}</h5>
                            <p class="villa-details-one__meta__name">Кроватей</p>
                        </div><!-- meta-item -->
                        <div class="villa-details-one__meta__item">
                            <div class="villa-details-one__meta__icon"><span class="icon-bath"></span></div>
                            <h5 class="villa-details-one__meta__number">{{ room.baths }}</h5>
                            <p class="villa-details-one__meta__name">Санузлов</p>
                        </div><!-- meta-item -->
                        <div class="villa-details-one__meta__item">
                            <div class="villa-details-one__meta__icon"><span class="icon-guests"></span></div>
                            <h5 class="villa-details-one__meta__number">{{ room.max_guest }}</h5>
                            <p class="villa-details-one__meta__name">Гостей</p>
                        </div><!-- meta-item -->

                    </div>
                </div>
            </div>
        </div>
    </section>


    <section class="villa-details-three">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">


                    <div class="villa-details-three__gallery">
                        <div class="villa-details-three__gallery__carousel villoz-owl__carousel owl-carousel owl-theme"
                             data-owl-options='{
                        "items": 1,
                        "margin": 0,
                        "loop": true,
                        "smartSpeed": 700,
                        "animateOut": "slideOutDown",
                        "autoplayTimeout": 6000,
                        "nav": true,
                        "navText": ["<span class=\"icon-left-arrow\"></span>","<span class=\"icon-right-arrow\"></span>"],
                        "dots": false,
                        "autoplay": true
                        }'>
                            {% for img in photos %}
                                <div class="item">
                                    <div class="villa-details-three__gallery__image">
                                        <img src="{{ img.image.url }}" alt="villa">
                                    </div>

                                </div>
                            {% endfor %}<!-- gallery-item -->
                        </div><!-- gallery-slider -->
                        <div class="villa-details-three__gallery__btns">

                            <a class="villoz-image-popup" href="#" data-gallery-options='

                                {
                            "items": [
                        {% for img in photos %}
                                {% if not forloop.last %}
                                    {"src": "{{ img.image.url }}"},
                                {% endif %}
                            {% if forloop.last %}
                                {"src": "{{ img.image.url }}"}
                            {% endif %}

                        {% endfor %}


                            ],
                            "gallery": {
                            "enabled": true
                            },
                            "type": "image"
                        }'>
                                <span class="icon-camera"></span><span
                                    class="villa-card-two__btns__count">{{ photos.count }}</span></a>
                        </div>
                    </div>


                    <div class="villa-details-three__content">
                        <h4 class="villa-details-three__content__title">Описание</h4>
                        <p class="villa-details-three__content__text">
                            {{ description }}
                        </p>
                    </div>

                    <div class="villa-details-three__content">
                        <h4 class="villa-details-three__content__title">Удобства</h4>
                        <ul>
                            <li>Кроватей в номере: {{ room.bads }}</li>
                            <li>Санузлов в номере: {{ room.baths }}</li>
                            <li>Максимальное количество гостей: {{ room.max_guest }}</li>
                            {% if room.wifi %}
                                <li> В номере бесплатный WI-FI</li>
                            {% endif %}
                            {% if room.parking %}
                                <li>Парковочное место входит в стоимость</li>
                            {% endif %}
                        </ul>

                    </div>

                    <div class="villa-details-three__content">
                        <h4 class="villa-details-three__content__title">{{ hotel.title }}</h4>
                        <p class="villa-details-three__content__text">
                            {{ hotel.description }}
                        </p>
                        <p class="villa-details-three__content__text">
                            {{ hotel.location_city }}, {{ hotel.location_strit }}, {{ hotel.location_building }}
                        </p>
                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="villa-details-sidebar">
                        <div class="villa-details-sidebar__booking">
                            <h4 class="villa-details-sidebar__booking__title">Забронировать</h4>
                            {% if request.user.is_authenticated %}
                                <form class="villa-details-sidebar__form" action="" method="post">
                                    {% csrf_token %}
                                    <div class="form-errors"> {{ from.non_field_errors }} </div>
                                    {% for f in form %}
                                        <div class="mt-2">
                                            <label for="{{ f.id_for_label }}"> {{ f.label }} </label> {{ f }}
                                        </div>
                                        <div class="form-errors"> {{ f.field_errors }} </div>
                                    {% endfor %}

                                    <div class="mt-2">
                                        <button type="submit" class="villoz-btn">
                                            <i>Забронировать</i>
                                            <span>Забронировать</span>
                                        </button>
                                    </div>
                                </form>


                                <!-- -->
                                {#                        <div class="row">#}
                                {#                            <section class="">#}
                                {#                                <div class="container">#}
                                {#                                    <form action="" method="post">#}
                                {#                                        {% csrf_token %}#}
                                {#                                        {{ form.as_p }}#}
                                {##}
                                {#                                        <div>#}
                                {#                                            <button type="submit" class="villoz-btn">#}
                                {#                                                <i>Забронировать</i>#}
                                {#                                                <span>Забронировать</span>#}
                                {#                                            </button>#}
                                {#                                        </div>#}
                                {##}
                                {#                                    </form>#}
                                {##}
                                {#                                </div>#}
                                {#                            </section>#}
                                {##}
                                {#                        </div>#}

                            {% else %}
                                <div class="row">
                                    <div class="container"><p>Бронирование доступно только зарегистрированным
                                        пользователям</p>

                                        <a href="{% url 'users:login' %}">Войти</a> /
                                        <a href="{% url 'users:register' %}">Регистрация</a></div>
                                </div>
                            {% endif %}
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </section>

    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    {##}
                    {#                    {% with comments.count as total_comments %}#}
                    {#                        <h2>#}
                    {#                            {{ total_comments }} комментариев#}
                    {#                        </h2>#}
                    {#                    {% endwith %}#}
                    {#                    {% for comment in comments %}#}
                    {#                        <div class="comment">#}
                    {#                            <p class="info">#}
                    {#                                Комментарий {{ forloop.counter }} от {{ comment.name }}#}
                    {#                                {{ comment.created }}#}
                    {#                            </p>#}
                    {#                            {{ comment.body|linebreaks }}#}
                    {#                        </div>#}
                    {#                    {% empty %}#}
                    {#                        <p>Нет комментариев.</p>#}
                    {#                    {% endfor %}#}
                    {#                    {% include "hotels/comment_form.html" %}#}
                </div>
            </div>
            <!-- Отображение комментариев -->
            {% with room.comments.count as total_comments %}
                <div class="product-details__comment wow fadeInUp" data-wow-delay="400ms">
                <h3 class="product-details__review-title">Комментариев: {{ total_comments }}</h3>
            {% endwith %}
            <!--Start Comment Box-->
            {% for comment in room.comments.all %}
                <div class="product-details__comment-box">
                    <h4 class="product-details__comment-box__meta">{{ comment.author.username }}<span
                            class="product-details__comment-box__date">{{ comment.created_date }}</span></h4>
                    <!-- comment-meta -->
                    <div class="product-details__comment-box__ratings">
                        {{ comment.rating }}
                        {% for _ in ''|ljust:comment.rating %}
                            <i class="fa fa-star"></i>
                        {% endfor %}
                    </div><!-- comment-ratings -->

                    <p class="product-details__comment-box__text">
                        {{ comment.text }}
                    </p>
                </div>
            {% endfor %}
            <!--End Comment Box-->

            </div>
            <!-- /.product-comment -->


            <!-- Форма для добавления комментария -->
            <form method="post" class="comments-form__form contact-form-validated product-details__form__form form-one">
                {% csrf_token %}
                {{ form3.as_p }}
                <div class="form-one__control form-one__control--full">
                    <button type="submit" class="villoz-btn villoz-btn--base">
                        <i>Оставить комментарий</i>
                        <span>Оставить комментарий</span>
                    </button>
                </div>
            </form>
        </div>
    </section>
    <script>
        $(document).ready(function () {
            const lb = lightbox();
        })


        $('form').submit(function (e) {
            e.preventDefault();

    </script>






{% endblock %}